### ISSUE TITLE
Conversion Problem

### ISSUE THREAD

**Issue by yeewc98** [ddddxxx/LyricsX#148]
I actually love this app a lot and it is super useful and user-friendly! One thing I wish to be fixed though is the conversion to tradition Chinese,which is not working most of the time... Everything else is perfect so I really wish for a fix on that!
Also I tried to donate and only to find out it doesn't support Hong Kong version of Alipay...If you can accept another way of donation, please tell me coz I would like to show my support to this awesome FREE app!!

**Comment by ddddxxx** [comment]
Chinese conversion problem (#125) has been fixed in 1.3.0.  [The beta version](https://github.com/ddddxxx/LyricsX/releases/tag/v1.3.0-beta.2) is available on GitHub, and will be released on App Store soon.

Thank you for your willingness to support, this means a lot to me. You can also star this project on GitHub, or leave comment on App Store :)
