### ISSUE TITLE
Please add support for AirPlay 1.

### ISSUE THREAD

**Issue by HUQIANHAO** [ddddxxx/LyricsX#168]
[Legacy AirPlay 1 has a buffer latency for precisely 2000ms](https://stackoverflow.com/questions/9997882/detecting-the-airplay-latency#11836972), so most players would compensate for this period of time (like iina). LyricsX has an offset feature, but it is always reset for another song. Please consider support AirPlay 1 specifically by adding compensation, or you can simply add an universal offset in the preference. Thank you!

---

[AirPlay 初代设置了一个两秒整的缓存](https://stackoverflow.com/questions/9997882/detecting-the-airplay-latency#11836972)，大部分播放器都会对这个缓存进行补偿（比如 iina）。LyricsX 有「歌词偏移」这个功能，但是每当切换到其他曲目（播完或切歌等），都会自动将这个偏移重置为 0。请考虑原生支持 AirPlay 初代，就像其他播放器一样加入补偿，或者也可以在偏好设置中单独加一个全局偏移设置。非常感谢！

**Comment by ddddxxx** [comment]
The [latency API](https://developer.apple.com/documentation/avfoundation/avaudiosession/1616500-outputlatency) doesn't seem to be present on macOS. And, hardcoding a compensation feels dirty. Since universal offset is [implemented](https://github.com/ddddxxx/LyricsX/commit/4eb28cd775cc0891e8ae52d6094177fd298677de), there won't be a dedicated AirPlay compensation.

**Comment by HUQIANHAO** [comment]
A universal offset is good enough, thank you.
