### ISSUE TITLE
Cask can't auto update to 1.4.1

### ISSUE THREAD

**Issue by mortyccp** [ddddxxx/LyricsX#178]
Cause brew cask formula auto update depends on `url "https://github.com/ddddxxx/LyricsX/releases/download/v#{version}/LyricsX.app.zip"`.

The latest version file name seem to be not in this format.
Would like to know it is intended or not since Apple didn't approve the new version.
Thanks.

**Comment by ddddxxx** [comment]
It's intended change in order to [integrate Sparkle with GitHub releases](https://yiqiu.me/2015/11/19/sparkle-update-on-github/). The file name will be LyricsX_{VERSION}+{BUILD}.

The cask formula is not maintained by myself, and I'm not very familiar with homebrew stuff. Do you have any idea to fix this?

**Comment by mortyccp** [comment]
Sorry, I am not the maintainer for the cask formula also.
@shatteringlass Do you have time to look at it?

**Comment by ddddxxx** [comment]
Fixed with Homebrew/homebrew-cask#52049. @shatteringlass thanks!
