### ISSUE TITLE
Furigana not shown for all Kanjis in Japanese lyrics

### ISSUE THREAD

**Issue by tianranwangcs** [ddddxxx/LyricsX#225]
It is usually the case that some Kanjis(汉字) in Japanese lyrics failed to be annotated with furigana(振假名), like the "见" and "谢" characters in the screenshot.
<img width="359" alt="screen shot 2018-12-23 at 19 51 43" src="https://user-images.githubusercontent.com/12750082/50390511-c04f9400-06ec-11e9-95fe-29d18af8d888.png">

**Comment by Windypper** [comment]
I guess that is probably because those are actually not Kanji. The API doesn't recognise the Simplified Chinese as Kanji which is used to generate furigana. So maybe the solution is to attach right lyrics (Japanese Kanjis and Kanas instead of Simplified Chinese characters) to the song.

**Comment by Windypper** [comment]
Because I am not the developer, I am not sure if it can be done as you wish, but I think it requires much work to judge the language of the lyrics or even every sentence (some songs may combine different languages). So if you want to do something on this, the only way I think is to communicate with the developer. Good luck!

**Comment by ddddxxx** [comment]
Could you please attach the lyrics file? For performance reason, only `U+4e00` ~ `U+9fc0` is annotated since v1.4.4.

**Comment by ddddxxx** [comment]
Chinese conversion won't affect Kanji annotation in next version. Enjoy!

**Comment by tianranwangcs** [comment]
@ddddxxx Thanks for solving this problem!
